function R = func_get_rot_matrix(a,b,g)
R = [[ cos(b)*cos(g), -cos(b)*sin(g), sin(b)]; ...
     [ cos(a)*sin(g) + cos(g)*sin(a)*sin(b), cos(a)*cos(g) - sin(a)*sin(b)*sin(g), -cos(b)*sin(a)];  ...
     [ sin(a)*sin(g) - cos(a)*cos(g)*sin(b), cos(g)*sin(a) + cos(a)*sin(b)*sin(g), cos(a)*cos(b)]];
end